# populate if using GitHub Actions
name: Example 1
on:
 push:
   branches: [ main ]
jobs:
 build:
   name: Build-job
   runs-on: self-hosted
   steps:
   - name: Checkout
     uses: actions/checkout@v2
   - name: Print message
     run: echo "Workflow is running on a self-hosted runner"

